# config 
lr: learning rate for gradient descent
max_iter: if gradient steps larger than max_iter, stop

# supporting functions


# initialization
W: (d,q) : np.zeros(d,q)
b: (q,) : np.zeros(q)

# fit(X,y)
## forward
z= X*W+b
y_hat= identity(z)
## gradient
err= y_hat-y
dw = 1/n*(err)X
db = np.mean(err)
## update
W= W-dw
b = b-db

# predict(X)
z= X*W+b
y_hat= identity(z)


In [34]:
from ml_algorithm_playground.linear.linear_regression import LinearRegression

In [35]:
from ml_algorithm_playground.utils.data_generation import make_regression

In [36]:
X,y=make_regression(
  n_samples = 10,
  n_features = 2,
  n_outputs = 2,
  noise = 0,
  seed = 42
)

In [37]:
X

array([[ 0.30471708, -1.03998411],
       [ 0.7504512 ,  0.94056472],
       [-1.95103519, -1.30217951],
       [ 0.1278404 , -0.31624259],
       [-0.01680116, -0.85304393],
       [ 0.87939797,  0.77779194],
       [ 0.0660307 ,  1.12724121],
       [ 0.46750934, -0.85929246],
       [ 0.36875078, -0.9588826 ],
       [ 0.8784503 , -0.04992591]])

In [38]:
y=y*10
y

array([[-17.56082103,  -3.98916207],
       [  5.82821244, -10.0848292 ],
       [-16.59623123,  11.77609076],
       [ -8.38580343,  -3.90315054],
       [-14.68103386,  -2.0887271 ],
       [  3.59987384, -10.71133398],
       [  9.37564561,  -5.71287803],
       [-15.65273262,  -5.37688455],
       [-16.68769582,  -4.55051222],
       [ -6.51756711,  -9.42581289]])

In [39]:
model = LinearRegression(lr=0.01,max_iter=1000)

In [40]:
model.fit(X,y)

In [41]:
y_pred=model.predict(X)

In [42]:
(y_pred-y)

array([[ 0.1585222 ,  0.05748378],
       [-0.1566845 , -0.05612093],
       [-0.36659838, -0.13376631],
       [-0.04433376, -0.01593594],
       [ 0.03494937,  0.01261717],
       [-0.0880527 , -0.03123514],
       [-0.3738436 , -0.13504591],
       [ 0.16127853,  0.05858781],
       [ 0.15742825,  0.05713097],
       [ 0.09150357,  0.0336472 ]])

In [43]:
y_pred

array([[-17.40229883,  -3.9316783 ],
       [  5.67152794, -10.14095012],
       [-16.96282961,  11.64232446],
       [ -8.43013719,  -3.91908648],
       [-14.64608448,  -2.07610992],
       [  3.51182114, -10.74256912],
       [  9.00180201,  -5.84792394],
       [-15.49145409,  -5.31829674],
       [-16.53026757,  -4.49338125],
       [ -6.42606354,  -9.39216569]])