# Config and Parameters

- lr: learning rate
- max_iter: maximum iterations
- tol: tolerance for stop using gradient norm

# Initialization
- Init weights and bias to zero

# supporting functions
- sigmoid: 1/(1+exp(-z))

# Fitting
- forward prop: y_hat = sigmoid(w*X+b)
- Loss: cross entropy: L = -1/n sum(y_i log(y_hat_i) + (1-y_i)*log(1-y_hat_i))
- Gradient: dw = (1/n) X^T*err , db = mean(error)
- Gradient descent： w = w - lr*dw, b = b-lr*db
- stop: iter> max_iter or |dw|<tol

# Prediction
- yhat = sigmoid(X*w+b)

In [51]:
from ml_algorithm_playground.linear.logistic_regression import LogisticRegression

In [52]:
n_samples,n_features = 10,4
seed= 42

import numpy as np

# Set a random seed for reproducibility
np.random.seed(42) # You can use any integer here

# Create a (5,4) numpy array with random values between 0 and 1
X = np.random.rand(n_samples, n_features)
print("Deterministic Random Array (using seed 42):\n", X)

Deterministic Random Array (using seed 42):
 [[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485 0.17052412]
 [0.06505159 0.94888554 0.96563203 0.80839735]
 [0.30461377 0.09767211 0.68423303 0.44015249]]


In [53]:
Y = np.random.randint(0,2,n_samples)
print("Deterministic Random Array (using seed 42):\n", Y)

Deterministic Random Array (using seed 42):
 [0 1 0 1 0 0 1 0 1 1]


In [54]:
model=LogisticRegression(treshold=0.5,lr=0.01, max_iter=1000, tol=1e-4)

In [55]:
model.fit(X,Y)

In [56]:
y_hat= model.predict(X)
print(f"y_hat: {y_hat}")

y_hat: [[0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]]


In [57]:
print(f"y: {Y}")

y: [0 1 0 1 0 0 1 0 1 1]
