Interview usually does not require implementing the whole decision tree from the scratch.

So this notebook will focus on the coding of the target function part:
1. entropy(labels) # decision tree greedily targeting minimizing entropy of the child nodes when selecting feature to split on
2. information_gain(labels) # decision tree greedily targeting maximizing the information gain when selecting feature to split on

In [1]:
import numpy as np

y = np.array([2, 2, 1, 0, 2, 1])

In [2]:
classes, counts = np.unique(y, return_counts=True)

In [4]:
classes

array([0, 1, 2])

In [5]:
counts

array([1, 2, 3])

In [7]:
p = counts/counts.sum()
p

array([0.16666667, 0.33333333, 0.5       ])

In [8]:
H = -np.sum(p * np.log2(p))
H

np.float64(1.4591479170272448)

In [24]:
def entropy(y):
    _,counts = np.unique(y, return_counts = True)
    p = counts/counts.sum()
    #print(p)
    H = - np.sum(p*np.log2(p))
    return H

In [25]:
entropy(y=[1,1,0,0,0,1,2,2])

np.float64(1.561278124459133)

In [26]:
def information_gain(y, y_left, y_right):
    H_y = entropy(y)
    H_y_left = entropy(y_left)
    H_y_right = entropy(y_right)
    p_left = len(y_left)/len(y)
    p_right = len(y_right)/len(y)
    IG = H_y - (p_left*H_y_left + p_right*H_y_right)
    return IG

In [27]:
information_gain(y=[1,1,0,0,0,1,2,2], y_left=[1,1,0,0], y_right=[0,1,2,2])

np.float64(0.31127812445913294)