### 1. Mount your Google Drive

First, you need to mount your Google Drive to make it accessible in Google Colab. This will prompt you to authenticate your Google account.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


### 2. Clone the GitHub repository to your Google Drive

Once your Drive is mounted, you can navigate to a directory within it (e.g., `MyDrive/GitHub_Repos`) and clone your GitHub repository there. Replace `YOUR_GITHUB_REPO_URL` with the actual URL of the repository you want to clone.

In [3]:
# Change to your desired directory on Google Drive
# For example, to create a 'GitHub_Repos' folder if it doesn't exist:
!mkdir -p /content/drive/MyDrive/Job_MLE
%cd /content/drive/MyDrive/Job_MLE

# Replace 'YOUR_GITHUB_REPO_URL' with the actual URL of the GitHub repository
!git clone https://github.com/EricWu23/ml-algorithm-playground.git

/content/drive/MyDrive/Job_MLE
Cloning into 'ml-algorithm-playground'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), done.


### 3. Verify the repository is cloned

You can then list the contents of the directory to ensure the repository was cloned successfully.

In [4]:
# List the contents of the current directory to see the cloned repository
!ls

ml-algorithm-playground


# K-Means

In [1]:
from ml_algorithm_playground.neighbors.kmeans import Kmeans

After running the above cells, your package should be set up. You can verify the installation by trying to import the `Kmeans` class, which should now work directly.

# Test

In [58]:
N =20
D = 4

In [59]:
import numpy as np

# Set a random seed for reproducibility
np.random.seed(42) # You can use any integer here

# Create a (5,4) numpy array with random values between 0 and 1
X = np.random.rand(N, D)
print("Deterministic Random Array (using seed 42):\n", X)

Deterministic Random Array (using seed 42):
 [[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485 0.17052412]
 [0.06505159 0.94888554 0.96563203 0.80839735]
 [0.30461377 0.09767211 0.68423303 0.44015249]
 [0.12203823 0.49517691 0.03438852 0.9093204 ]
 [0.25877998 0.66252228 0.31171108 0.52006802]
 [0.54671028 0.18485446 0.96958463 0.77513282]
 [0.93949894 0.89482735 0.59789998 0.92187424]
 [0.0884925  0.19598286 0.04522729 0.32533033]
 [0.38867729 0.27134903 0.82873751 0.35675333]
 [0.28093451 0.54269608 0.14092422 0.80219698]
 [0.07455064 0.98688694 0.77224477 0.19871568]
 [0.00552212 0.81546143 0.70685734 0.72900717]
 [0.77127035 0.07404465 0.35846573 0.11586906]]


In [65]:
clusters = Kmeans(k=4, max_iters=100, tol=0, rng = np.random.default_rng(seed=42))

In [66]:
clusters.fit(X)

Iteration: 1, Shift: 0.0
Iteration: 2, Shift: 0.0
Iteration: 3, Shift: 0.0
Iteration: 4, Shift: 0.0
Iteration: 5, Shift: 0.0
Iteration: 6, Shift: 0.0
Iteration: 7, Shift: 0.0
Iteration: 8, Shift: 0.0
Iteration: 9, Shift: 0.0
Iteration: 10, Shift: 0.0
Iteration: 11, Shift: 0.0
Iteration: 12, Shift: 0.0
Iteration: 13, Shift: 0.0
Iteration: 14, Shift: 0.0
Iteration: 15, Shift: 0.0
Iteration: 16, Shift: 0.0
Iteration: 17, Shift: 0.0
Iteration: 18, Shift: 0.0
Iteration: 19, Shift: 0.0
Iteration: 20, Shift: 0.0
Iteration: 21, Shift: 0.0
Iteration: 22, Shift: 0.0
Iteration: 23, Shift: 0.0
Iteration: 24, Shift: 0.0
Iteration: 25, Shift: 0.0
Iteration: 26, Shift: 0.0
Iteration: 27, Shift: 0.0
Iteration: 28, Shift: 0.0
Iteration: 29, Shift: 0.0
Iteration: 30, Shift: 0.0
Iteration: 31, Shift: 0.0
Iteration: 32, Shift: 0.0
Iteration: 33, Shift: 0.0
Iteration: 34, Shift: 0.0
Iteration: 35, Shift: 0.0
Iteration: 36, Shift: 0.0
Iteration: 37, Shift: 0.0
Iteration: 38, Shift: 0.0
Iteration: 39, Shift:

In [67]:
clusters.tol

0

In [68]:
clusters._shift

np.float64(0.0)

In [69]:
clusters._iteration_counter

101

In [70]:
Y=clusters.predict(X)

In [71]:
Y

array([0, 1, 3, 2, 1, 2, 3, 2, 0, 2, 1, 1, 2, 3, 1, 2, 1, 0, 0, 2])

In [72]:
# Set a random seed for reproducibility
np.random.seed(42) # You can use any integer here

# Create a (5,4) numpy array with random values between 0 and 1
X = np.random.rand(10, D)
print("Deterministic Random Array (using seed 42):\n", X)

Deterministic Random Array (using seed 42):
 [[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485 0.17052412]
 [0.06505159 0.94888554 0.96563203 0.80839735]
 [0.30461377 0.09767211 0.68423303 0.44015249]]


In [73]:
Y=clusters.predict(X)

In [74]:
Y

array([0, 1, 3, 2, 1, 2, 3, 2, 0, 2])

In [75]:
clusters._centroids

array([[0.12991612, 0.92548705, 0.79418202, 0.58369467],
       [0.20175102, 0.42952152, 0.17037996, 0.6190535 ],
       [0.57828311, 0.14660052, 0.56036219, 0.34402831],
       [0.66556131, 0.7960253 , 0.27271942, 0.80200618]])